-- CREATE DATABASE
CREATE DATABASE DKTE;

-- USE DATABASE
USE DKTE;

-- SHOW TABLES IN DATABASE;
SHOW TABLES;

-- CREATE TABLES IN DATABASE
CREATE TABLE student (roll int(4),name VARCHAR(50),marks int(5));

-- print the table
SELECT * FROM student;

-- INSERT DATA INTO TABLE
INSERT INTO STUDENT VALUES(10,'HARIS',50);
INSERT INTO STUDENT VALUES (11, 'NAVANATH', 95);
INSERT INTO STUDENT VALUES (12, 'AAKASH', 88);
INSERT INTO STUDENT VALUES (13, 'RAVI', 72);
INSERT INTO STUDENT VALUES (14, 'SARA', 66);
